// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

type Cat struct {
	ID                int32
	Name              string
	YearsOfExperience int32
	Breed             string
	Salary            int32
}
